const foods = [
  {
    id: '1',
    category: 'Popular',
    name: 'Crispy',
    price: '59,000',
    image: require('../assets/popular/crispy.png'),
    rating: require('../assets/rating/rating-45.png'),
  },
  {
    id: '2',
    category: ['Popular', 'Burgers'],
    name: 'Big Mac Burger',
    price: '76,000',
    image: require('../assets/popular/burger.png'),
    rating: require('../assets/rating/rating-50.png'),
  },
  {
    id: '3',
    category: 'Burgers',
    name: 'Cheese Bacon',
    price: '56,000',
    image: require('../assets/burgers/cheesebacon.png'),
    rating: require('../assets/rating/rating-35.png'),
  },
  {
    id: '4',
    category: 'Burgers',
    name: 'Cheese Burger',
    price: '39,000',
    image: require('../assets/burgers/cheeseburger.png'),
    rating: require('../assets/rating/rating-20.png'),
  },
  {
    id: '5',
    category: 'Burgers',
    name: 'Cheese Deluxe',
    price: '89,000',
    image: require('../assets/burgers/cheesedeluxe.png'),
    rating: require('../assets/rating/rating-40.png'),
  },
  {
    id: '6',
    category: 'Burgers',
    name: 'Double Cheese Burger',
    price: '66,000',
    image: require('../assets/burgers/doublecheeseburger.png'),
    rating: require('../assets/rating/rating-30.png'),
  },
  {
    id: '7',
    category: ['Popular', 'Snacks & Sides'],
    name: 'Nuggets',
    price: '49,000',
    image: require('../assets/popular/nuggets.png'),
    rating: require('../assets/rating/rating-45.png'),
  },
  {
    id: '8',
    category: ['Popular', 'Snacks & Sides'],
    name: 'French fries',
    price: '29,000',
    image: require('../assets/snacks_sides/chips.png'),
    rating: require('../assets/rating/rating-40.png'),
  },
  {
    id: '9',
    category: 'Snacks & Sides',
    name: 'Burrito',
    price: '39,000',
    image: require('../assets/snacks_sides/burrito.png'),
    rating: require('../assets/rating/rating-25.png'),
  },
  {
    id: '10',
    category: 'Snacks & Sides',
    name: 'Hot Cakes',
    price: '35,000',
    image: require('../assets/snacks_sides/hotcakes.png'),
    rating: require('../assets/rating/rating-35.png'),
  },
  {
    id: '11',
    category: 'Drinks & Sweets',
    name: 'Coca Cola',
    price: '22,000',
    image: require('../assets/drinks_sweets/coke.png'),
    rating: require('../assets/rating/rating-30.png'),
  },
  {
    id: '12',
    category: 'Drinks & Sweets',
    name: 'Fanta',
    price: '22,000',
    image: require('../assets/drinks_sweets/fanta.png'),
    rating: require('../assets/rating/rating-30.png'),
  },
  {
    id: '13',
    category: 'Drinks & Sweets',
    name: 'Sprite',
    price: '22,000',
    image: require('../assets/drinks_sweets/sprite.png'),
    rating: require('../assets/rating/rating-35.png'),
  },
  {
    id: '14',
    category: 'Drinks & Sweets',
    name: 'Caramel Sundae',
    price: '29,000',
    image: require('../assets/drinks_sweets/sundae1.png'),
    rating: require('../assets/rating/rating-40.png'),
  },
  {
    id: '15',
    category: 'Drinks & Sweets',
    name: 'Chocolate Sundae',
    price: '29,000',
    image: require('../assets/drinks_sweets/sundae2.png'),
    rating: require('../assets/rating/rating-45.png'),
  },
  {
    id: '16',
    category: 'Drinks & Sweets',
    name: 'Strawberry Sundae',
    price: '29,000',
    image: require('../assets/drinks_sweets/sundae3.png'),
    rating: require('../assets/rating/rating-30.png'),
  },
  {
    id: '17',
    category: 'Drinks & Sweets',
    name: 'Vanilla Icecream',
    price: '10,000',
    image: require('../assets/drinks_sweets/vanillacone.png'),
    rating: require('../assets/rating/rating-40.png'),
  },
];

export default foods;
